//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPF_FITNESS_CENTER.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Coach> Coach { get; set; }
        public virtual DbSet<Conference> Conference { get; set; }
        public virtual DbSet<Moderator> Moderator { get; set; }
        public virtual DbSet<Organizator> Organizator { get; set; }
        public virtual DbSet<Participant> Participant { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
